/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface TraderAccount {
    }
    interface TraderAccountItem {
        "account": any;
    }
    interface TraderAccountList {
        "accountCount": any;
        "accounts": any;
    }
    interface TraderApplication {
    }
    interface TraderDashboard {
    }
    interface TraderHeader {
    }
    interface TraderLogin {
    }
    interface TraderNavigation {
    }
    interface TraderSpinner {
    }
    interface TraderUserView {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTraderAccountElement extends Components.TraderAccount, HTMLStencilElement {
    }
    var HTMLTraderAccountElement: {
        prototype: HTMLTraderAccountElement;
        new (): HTMLTraderAccountElement;
    };
    interface HTMLTraderAccountItemElement extends Components.TraderAccountItem, HTMLStencilElement {
    }
    var HTMLTraderAccountItemElement: {
        prototype: HTMLTraderAccountItemElement;
        new (): HTMLTraderAccountItemElement;
    };
    interface HTMLTraderAccountListElement extends Components.TraderAccountList, HTMLStencilElement {
    }
    var HTMLTraderAccountListElement: {
        prototype: HTMLTraderAccountListElement;
        new (): HTMLTraderAccountListElement;
    };
    interface HTMLTraderApplicationElement extends Components.TraderApplication, HTMLStencilElement {
    }
    var HTMLTraderApplicationElement: {
        prototype: HTMLTraderApplicationElement;
        new (): HTMLTraderApplicationElement;
    };
    interface HTMLTraderDashboardElement extends Components.TraderDashboard, HTMLStencilElement {
    }
    var HTMLTraderDashboardElement: {
        prototype: HTMLTraderDashboardElement;
        new (): HTMLTraderDashboardElement;
    };
    interface HTMLTraderHeaderElement extends Components.TraderHeader, HTMLStencilElement {
    }
    var HTMLTraderHeaderElement: {
        prototype: HTMLTraderHeaderElement;
        new (): HTMLTraderHeaderElement;
    };
    interface HTMLTraderLoginElement extends Components.TraderLogin, HTMLStencilElement {
    }
    var HTMLTraderLoginElement: {
        prototype: HTMLTraderLoginElement;
        new (): HTMLTraderLoginElement;
    };
    interface HTMLTraderNavigationElement extends Components.TraderNavigation, HTMLStencilElement {
    }
    var HTMLTraderNavigationElement: {
        prototype: HTMLTraderNavigationElement;
        new (): HTMLTraderNavigationElement;
    };
    interface HTMLTraderSpinnerElement extends Components.TraderSpinner, HTMLStencilElement {
    }
    var HTMLTraderSpinnerElement: {
        prototype: HTMLTraderSpinnerElement;
        new (): HTMLTraderSpinnerElement;
    };
    interface HTMLTraderUserViewElement extends Components.TraderUserView, HTMLStencilElement {
    }
    var HTMLTraderUserViewElement: {
        prototype: HTMLTraderUserViewElement;
        new (): HTMLTraderUserViewElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "trader-account": HTMLTraderAccountElement;
        "trader-account-item": HTMLTraderAccountItemElement;
        "trader-account-list": HTMLTraderAccountListElement;
        "trader-application": HTMLTraderApplicationElement;
        "trader-dashboard": HTMLTraderDashboardElement;
        "trader-header": HTMLTraderHeaderElement;
        "trader-login": HTMLTraderLoginElement;
        "trader-navigation": HTMLTraderNavigationElement;
        "trader-spinner": HTMLTraderSpinnerElement;
        "trader-user-view": HTMLTraderUserViewElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface TraderAccount {
    }
    interface TraderAccountItem {
        "account"?: any;
    }
    interface TraderAccountList {
        "accountCount"?: any;
        "accounts"?: any;
    }
    interface TraderApplication {
    }
    interface TraderDashboard {
    }
    interface TraderHeader {
    }
    interface TraderLogin {
        "onUserLoggedIn"?: (event: CustomEvent<any>) => void;
    }
    interface TraderNavigation {
    }
    interface TraderSpinner {
    }
    interface TraderUserView {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "trader-account": TraderAccount;
        "trader-account-item": TraderAccountItem;
        "trader-account-list": TraderAccountList;
        "trader-application": TraderApplication;
        "trader-dashboard": TraderDashboard;
        "trader-header": TraderHeader;
        "trader-login": TraderLogin;
        "trader-navigation": TraderNavigation;
        "trader-spinner": TraderSpinner;
        "trader-user-view": TraderUserView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "trader-account": LocalJSX.TraderAccount & JSXBase.HTMLAttributes<HTMLTraderAccountElement>;
            "trader-account-item": LocalJSX.TraderAccountItem & JSXBase.HTMLAttributes<HTMLTraderAccountItemElement>;
            "trader-account-list": LocalJSX.TraderAccountList & JSXBase.HTMLAttributes<HTMLTraderAccountListElement>;
            "trader-application": LocalJSX.TraderApplication & JSXBase.HTMLAttributes<HTMLTraderApplicationElement>;
            "trader-dashboard": LocalJSX.TraderDashboard & JSXBase.HTMLAttributes<HTMLTraderDashboardElement>;
            "trader-header": LocalJSX.TraderHeader & JSXBase.HTMLAttributes<HTMLTraderHeaderElement>;
            "trader-login": LocalJSX.TraderLogin & JSXBase.HTMLAttributes<HTMLTraderLoginElement>;
            "trader-navigation": LocalJSX.TraderNavigation & JSXBase.HTMLAttributes<HTMLTraderNavigationElement>;
            "trader-spinner": LocalJSX.TraderSpinner & JSXBase.HTMLAttributes<HTMLTraderSpinnerElement>;
            "trader-user-view": LocalJSX.TraderUserView & JSXBase.HTMLAttributes<HTMLTraderUserViewElement>;
        }
    }
}
